### ISSUE TITLE
Could you explain how to add games

### ISSUE THREAD

**Issue by ghost** [clchiou/chrome-dosbox#1]

**Comment by clchiou** [comment]
There is a toolbar at the bottom of the DOSBox window. Click "Import Dir" and select the folder containing your game. The importing may take up to a minute if your game is really large. Otherwise it should be instantaneous. Then restart DOSBox and you should find the imported folder in C:\ drive. Enjoy your game!

**Comment by ghost** [comment]
it looks like your only able to play one game on it can you make a fix for
that

**Comment by clchiou** [comment]
I think you may import as many games as there are disk space left, and you may open multiple DOSBox windows with each playing different game. Would you be more elaborate on "play one game" limitation please?

**Comment by ghost** [comment]
Never mind i actually got it to work
